#!/bin/bash

source .env

base_url=https://api.linode.com/v4

licall() {
	curl -H "Authorization: Bearer $LINODE_TOKEN" $base_url/domains/$DOMAIN_ID/records
}

# backup: https://checkip.amazonaws.com
IP=$(curl --silent https://api.ipify.org/)

if [[ ! $IP =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
	echo "Invalid looking IP: $IP" >&2
	exit 1
fi

# TODO: Check if IP changed and exit if not.
# TODO: allow the DOMAIN and RECORD to be looked up by name

#curl -v -H "Authorization: Bearer $LINODE_TOKEN" $base_url/domains/$DOMAIN_ID/records/$DOMAIN_RECORD_ID 
#exit

curl -XPUT -H "Authorization: Bearer $LINODE_TOKEN" -H "Content-Type: application/json" $base_url/domains/$DOMAIN_ID/records/$DOMAIN_RECORD_ID -d @- <<JSON
{
	"target": "${IP}"
}
JSON

