#!/bin/bash

source .env

base_url=https://api.linode.com/v4
state_file=.state

licall() {
	curl -H "Authorization: Bearer $LINODE_TOKEN" $base_url/domains/$DOMAIN_ID/records
}

get_previous_ip() {
	if [ -e $state_file ]; then
		cat $state_file
	fi
}

# backup: https://checkip.amazonaws.com
IP=$(curl --silent https://api.ipify.org/)

if [[ ! $IP =~ ^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
	echo "Invalid looking IP: $IP" >&2
	exit 1
fi

previous_ip=$(get_previous_ip)

if [ "$IP" = "$previous_ip" ]; then
	echo "IP unchanged ($IP)" >&2
	exit
fi

echo "Updating ip address from $previous_ip to $IP" >&2

# TODO: allow the DOMAIN and RECORD to be looked up by name

#curl -v -H "Authorization: Bearer $LINODE_TOKEN" $base_url/domains/$DOMAIN_ID/records/$DOMAIN_RECORD_ID 
#exit

# cat <<JSON
curl -XPUT -H "Authorization: Bearer $LINODE_TOKEN" -H "Content-Type: application/json" $base_url/domains/$DOMAIN_ID/records/$DOMAIN_RECORD_ID -d @- <<JSON
{
	"target": "${IP}"
}
JSON

echo $IP > $state_file